services:
  pdf-document-layout-analysis-gpu:
    extends:
      file: docker-compose.yml
      service: pdf-document-layout-analysis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - RESTART_IF_NO_GPU=$RESTART_IF_NO_GPU